services:
  # API / Backend
  - type: web
    name: safeeely-api
    env: node
    plan: free
    rootDir: . # Use root to get access to all tools
    buildCommand: npm install
    startCommand: npm start -w packages/api
    envVars:
      - key: REVIEWS_URL
        value: https://yourdomain.com # Replace with your Vercel URL
      - fromGroup: safeeely-common

  # Telegram Bot
  - type: web
    name: safeeely-telegram
    env: node
    plan: free
    rootDir: . # Use root to get access to all tools
    buildCommand: npm install
    startCommand: npm start -w packages/telegram
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - fromGroup: safeeely-common

  # Discord Bot
  - type: web
    name: safeeely-discord
    env: node
    plan: free
    rootDir: . # Use root to get access to all tools
    buildCommand: npm install
    startCommand: npm start -w packages/discord
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - fromGroup: safeeely-common

envVarGroups:
  - name: safeeely-common
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
