export const ALL_COUNTRIES = [
    { code: 'GLOBAL', name: 'Worldwide / Global', flag: '🌍' },
    { code: 'US', name: 'United States', flag: 'us' },
    { code: 'GB', name: 'United Kingdom', flag: 'gb' },
    { code: 'NG', name: 'Nigeria', flag: 'ng' },
    { code: 'IN', name: 'India', flag: 'in' },
    { code: 'CA', name: 'Canada', flag: 'ca' },
    { code: 'AU', name: 'Australia', flag: 'au' },
    { code: 'NZ', name: 'New Zealand', flag: 'nz' },
    { code: 'ZA', name: 'South Africa', flag: 'za' },
    { code: 'GH', name: 'Ghana', flag: 'gh' },
    { code: 'KE', name: 'Kenya', flag: 'ke' },
    { code: 'RW', name: 'Rwanda', flag: 'rw' },
    { code: 'UG', name: 'Uganda', flag: 'ug' },
    { code: 'AE', name: 'United Arab Emirates', flag: 'ae' },
    { code: 'SG', name: 'Singapore', flag: 'sg' },
    { code: 'PH', name: 'Philippines', flag: 'ph' },
    { code: 'MY', name: 'Malaysia', flag: 'my' },
    { code: 'PK', name: 'Pakistan', flag: 'pk' },
    { code: 'BD', name: 'Bangladesh', flag: 'bd' },
    { code: 'DE', name: 'Germany', flag: 'de' },
    { code: 'FR', name: 'France', flag: 'fr' },
    { code: 'ES', name: 'Spain', flag: 'es' },
    { code: 'IT', name: 'Italy', flag: 'it' },
    { code: 'NL', name: 'Netherlands', flag: 'nl' },
    { code: 'SE', name: 'Sweden', flag: 'se' },
    { code: 'CH', name: 'Switzerland', flag: 'ch' },
    { code: 'IE', name: 'Ireland', flag: 'ie' },
    { code: 'BR', name: 'Brazil', flag: 'br' },
    { code: 'MX', name: 'Mexico', flag: 'mx' },
    { code: 'JP', name: 'Japan', flag: 'jp' },
    { code: 'KR', name: 'South Korea', flag: 'kr' },
    { code: 'CN', name: 'China', flag: 'cn' },
    { code: 'SA', name: 'Saudi Arabia', flag: 'sa' },
    { code: 'EG', name: 'Egypt', flag: 'eg' },
    { code: 'MA', name: 'Morocco', flag: 'ma' },
    { code: 'AR', name: 'Argentina', flag: 'ar' },
    { code: 'CO', name: 'Colombia', flag: 'co' },
    { code: 'TR', name: 'Turkey', flag: 'tr' },
    { code: 'ID', name: 'Indonesia', flag: 'id' },
    { code: 'VN', name: 'Vietnam', flag: 'vn' },
    { code: 'TH', name: 'Thailand', flag: 'th' },
    { code: 'PL', name: 'Poland', flag: 'pl' },
    { code: 'UA', name: 'Ukraine', flag: 'ua' },
    { code: 'AT', name: 'Austria', flag: 'at' }
];
